server: 
  port: 8001
  contextPath: /user-service
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password: